version: '3'
services:
  db:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  web:
    build: ./nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/mycode
      - ./nginx/conf.d/django.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    depends_on:
      - app
    restart: always

  app:
    build: ./django
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/tmp.log
    volumes:
      - ./src:/home/mycode
    expose:
      - "8001"
    depends_on:
      - db
    restart: always

volumes:
  db-data:

